language: objective-c
osx_image: xcode11.3

install:
  - brew install swiftlint swiftformat
  - cd ./Demo; pod install

script:
  - xcodebuild -workspace WKJavaScriptController-Demo.xcworkspace -scheme WKJavaScriptController-Demo -destination "platform=iOS Simulator,name=iPhone 7,OS=11.4" -configuration Debug ONLY_ACTIVE_ARCH=NO > >(xcpretty -c)

notifications:
  email: false
  slack:
    rooms:
      secure: bTrvofwn1zmzN8r+2wayyYAwzLyKdqk9lFEL2ufAqduouAEW4f6aWyupnvHFqWpSJkuBdHpEM1tnUTyhUUdKodn9AkkYlPEEYXOfshRipsxwCnnqjqdvVlNqn3bjlc3gq7FEDkYqBBrT69C8xcf5MqgfrqjRq+E1QvZuxg/P9THSoXPsysHUmbzbBN5g+zMZL0RmxGGSKLGC7QUPZyVxbZMX+yxry7P1xx1xrHf2b+yKhTIousmYPvFnzyxx5M7D5mHmGbkh24ELVHoCDTJid9S14Y0y8KnzTwtlPG2JuHAMaUDeXjSgAE7Bb0uFliXyQc2Zo/i6+ybDqXBiLLcczmJluuWNYi5Q6CTzmKAYoqQ8EOuYGIGNRIj1CJ1PXNz1exeayrXnoN2ZEYZXt+Sw1FBbrKzQkDugESVDlx7A6HDa8oKT+0Teyu4CD42Vs00KcNvCypzwYsZrGfo+x4RRjbJohWImHzczXEoYmIniKaP8XhBNow7QEx/SGnvcIkeh4Ww0wvfIztRehIJFbCEVUxwCUmwjpOgg032O3xgNR89pLOT7EZ1R4T+4ZFuTbxOqA1Rn1zM7NZxN+oduD1sNgT1mpVfmyQZfdtvxGq+Lh94pkT61KWZURUl+UhBOz8JQz/EUs6U9+1c7lh0OjP5dhyWotLiKxBYN51pqsLkz7TM=
    on_success: change
