language: objective-c
osx_image: xcode10

install:
  - cd ./WKJavaScriptController-Demo; pod install

script:
  - xcodebuild -workspace WKJavaScriptController-Demo.xcodeproj/project.xcworkspace -scheme WKJavaScriptController-Demo -sdk "iphonesimulator" -destination "platform=iOS Simulator,name=iPhone 7,OS=11.4" -configuration Debug ONLY_ACTIVE_ARCH=NO | xcpretty -c

notifications:
  email: false
  slack:
    rooms:
      - 'rididev:KMm0EBQYY1ThicCJo0CwYb5U'
    on_success: change
